### ISSUE TITLE
unable to  pay  using  command line 

### ISSUE THREAD

**Issue by staier** [mazaclub/electrum-dash#2]
Hi. 
Release branch  4.2.1
i cannot  send  using  payto  command line.
address is not  recognized and electrum tries to  query DNS  system with the  payto address.

./electrum-dash payto Xsih4hf4QLEA2RqE1s18hydBkg37111NbH 1.0
Error: Cannot read config file.
Password:
Traceback (most recent call last):
  File "./electrum-dash", line 346, in run_cmdline
    result = func(*args)
  File "/home/sergey/electrum-dash/lib/commands.py", line 70, in func_wrapper
    return func(*args)
  File "/home/sergey/electrum-dash/lib/commands.py", line 422, in payto
    tx = self._mktx([(destination, amount)], tx_fee, change_addr, domain, nocheck, unsigned)
  File "/home/sergey/electrum-dash/lib/commands.py", line 381, in _mktx
    address = self._resolver(address)
  File "/home/sergey/electrum-dash/lib/commands.py", line 344, in _resolver
    out = self.contacts.resolve(x)
  File "/home/sergey/electrum-dash/lib/contacts.py", line 29, in resolve
    out = self.resolve_openalias(k)
  File "/home/sergey/electrum-dash/lib/contacts.py", line 43, in resolve_openalias
    records, validated = dnssec.query(url, dns.rdatatype.TXT)
  File "/home/sergey/electrum-dash/lib/dnssec.py", line 256, in query
    out = resolver.query(url, rtype)
  File "/usr/lib/python2.7/dist-packages/dns/resolver.py", line 903, in query
    raise NXDOMAIN
NXDOMAIN

i traced down  the  problem  to :

def is_address(addr):
    ADDRESS_RE = re.compile('[1-9A-HJ-NP-Za-km-z]{26,}\\Z')
    if not ADDRESS_RE.match(addr):
        return False
    try:
        addrtype, h = bc_address_to_hash_160(addr)
    except Exception:
        return False
    if addrtype not in [76, 16]:
        return False
    return addr == hash_160_to_bc_address(h, addrtype)# for some reason   here it does not  validate

**Comment by staier** [comment]
invalid ,  i  made a mistake,  sorry .
